application: aqua-teacher
version: 1-1-1
runtime: go
api_version: go1
default_expiration: "7d"
instance_class: F1
automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: 1
  min_pending_latency: 3000ms
  max_pending_latency: automatic
  max_concurrent_requests: 80
skip_files:
  - ^(.*/)?.*/node_modules/.*
  - ^(.*/)?.*/test/.*

handlers:

# main

- url: /(.*\.(gif|png|jpg|pdf))
  static_files: static/\1
  upload: static/img/(.*\.(gif|png|jpg|pdf))

- url: /(favicon.ico)
  static_files: static/img/\1
  upload: static/img/favicon.ico

- url: /css/(.*\.(css|map))
  static_files: static/css/\1
  upload: static/css/(.*\.(css|map))

- url: /js/(.*\.(js|map))
  static_files: static/js/\1
  upload: static/js/(.*\.(js|map))

- url: /font/(.*\.(eot|svg|ttf|woff))
  static_files: static/font/\1
  upload: static/font/(.*\.(eot|svg|ttf|woff))

- url: /view/(.*\.html)
  static_files: static/view/\1
  upload: static/view/(.*\.html)

- url: /
  static_files: static/index.html
  upload: static/index.html
  
- url: /competition
  static_files: static/index.html
  upload: static/index.html

- url: /comprehensive
  static_files: static/index.html
  upload: static/index.html

- url: /all
  static_files: static/index.html
  upload: static/index.html

- url: /submission
  static_files: static/index.html
  upload: static/index.html
  
- url: /posted_content
  static_files: static/index.html
  upload: static/index.html

- url: /googled39548f713433868.html
  static_files: static/googled39548f713433868.html
  upload: static/googled39548f713433868.html

- url: /bower_components
  static_dir: bower_components/

- url: /api/.*
  script: _go_app
  
# admin
  
- url: /admin
  static_files: static/view/admin/index.html
  login: admin
  upload: static/view/admin/index.html

- url: /admin/(.*\.html)
  static_files: static/view/admin/\1
  login: admin
  upload: static/view/admin/(.*\.html)